config/routes.rb
Rails.application.routes.draw do
  mathjax 'mathjax'

  # Routes for GraphGist portal
  get 'graph_gists/submit' => 'graph_gists#submit'
  get 'graph_gists/preview' => 'graph_gists#preview', as: :graph_gist_preview

  get 'graph_gists/search' => 'graph_gists#search'

  # Routes for asset_portal
  resources :groups
  root 'assets#home'

  devise_for :users

  resources :categories
  resources :groups do
    member do
      get :users_to_add
    end
  end
  resources :users

  get 'models' => 'models#index', as: :models
  get 'models/:name' => 'models#show', as: :model

  get 'authorizables/user_and_group_search.json' => 'authorizables#user_and_group_search'
  get 'authorizables/:model_slug/:id.:format' => 'authorizables#show'
  put 'authorizables/:model_slug/:id.:format' => 'authorizables#update'

  get ':model_slug' => 'assets#index', as: :assets
  get ':model_slug/:id' => 'assets#show', as: :asset
  get ':model_slug/:id/edit' => 'assets#edit', as: :edit_asset
  patch ':model_slug/:id' => 'assets#update'
end

app/models/group.rb
class Group
  include Neo4j::ActiveNode
  property :name, type: String

  property :created_at
  property :updated_at

  has_one :in, :parent, model_class: :Group, type: :HAS_SUBGROUP
  has_many :out, :sub_groups, model_class: :Group, type: :HAS_SUBGROUP

  has_many :in, :members, model_class: :User, origin: :groups

  def self.roots
    all(:group).where('NOT(group<-[:HAS_SUBGROUP]-())')
  end

  def self.for_query(query_string)
    query_regex = Regexp.new('.*' + query_string.gsub(/[\s\*]+/, '.*') + '.*', 'i')

    as(:group)
      .where('group.name =~ {query}')
      .params(query: query_regex)
  end

  def addable_users
    User.as(:user)
      .groups(:group, nil, optional: true)
      .where('group.uuid <> ?', id)
      .query.with(:user)
      .proxy_as(User, :user)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :require_admin

  before_action :set_group, only: [:show, :edit, :update, :destroy, :users_to_add]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.roots
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def users_to_add
    render json: @group.addable_users
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def group_params
    params[:group][:member_ids].reject!(&:blank?)

    params[:group]
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.slim
= form_for @group, html: {class: 'ui form'} do |f|
  - if @group.errors.any?
    #error_explanation.ui.warning.message
      i.close.icon
      .header
        = "#{pluralize(@group.errors.count, "error")} prohibited this group from being saved:"
      .ui.segments
        - @group.errors.full_messages.each do |message|
          .ui.segment
            p = message

  = f.hidden_field :parent_id, value: params[:parent_id] || @group.parent_id

  .field
    label Name
    = f.text_field :name

  .field
    label Users
    = f.select :member_ids, options_from_collection_for_select(User.order(:name), :id, :name, @group.member_ids), {}, multiple: '', id: 'user-list-dropdown', class: 'ui dropdown'

    coffee:
      $('select.ui.dropdown').dropdown()



  .actions = f.submit class: 'ui primary button'

/= javascript_include_tag 'ember_apps/user_list_dropdown', 'data-turbolinks-track' => true

app/views/groups/_list.html.slim
- groups.each do |group|
  tr
    td style="padding-left: #{indentation * 10}px"
      i.caret.right.icon
      = group.name
    td = link_to action: :new, parent_id: group do
      i.sitemap.large.icon
      | Create Subgroup
    td = link_to group do
      i.unhide.large.icon
      | Show
    td = link_to edit_group_path(group) do
      i.edit.large.icon
      | Edit
    td = link_to group, data: {:confirm => 'Are you sure?'}, :method => :delete do
      i.remove.large.icon
      | Delete

  = render partial: 'list', locals: {groups: group.sub_groups, indentation: indentation + 1}

app/views/groups/edit.html.slim
h1 Editing group

== render 'form'

= link_to 'Show', @group
'|
= link_to 'Back', groups_path

app/views/groups/index.html.slim
h1 Listing groups

table.ui.padded.table
  thead
    tr
      th Name
      th
      th
      th
      th

  tbody
    = render partial: 'list', locals: {groups: @groups, indentation: 1}


br

= link_to 'New Group', new_group_path

app/views/groups/new.html.slim
h1 New group

== render 'form'

= link_to 'Back', groups_path

app/views/groups/show.html.slim
p#notice = notice

h1 Viewing group:

h2 = @group.name

h3 Members

.ui.segments
  - @group.members.each do |member|
    .ui.segment
      = link_to member.name, member

= link_to 'Edit', edit_group_path(@group)
'|
= link_to 'Back', groups_path