config/routes.rb
Rails.application.routes.draw do
  mathjax 'mathjax'

  # Routes for GraphGist portal
  get 'graph_gists/submit' => 'graph_gists#submit'
  get 'graph_gists/preview' => 'graph_gists#preview', as: :graph_gist_preview

  get 'graph_gists/search' => 'graph_gists#search'

  # Routes for asset_portal
  resources :groups
  root 'assets#home'

  devise_for :users

  resources :categories
  resources :groups do
    member do
      get :users_to_add
    end
  end
  resources :users

  get 'models' => 'models#index', as: :models
  get 'models/:name' => 'models#show', as: :model

  get 'authorizables/user_and_group_search.json' => 'authorizables#user_and_group_search'
  get 'authorizables/:model_slug/:id.:format' => 'authorizables#show'
  put 'authorizables/:model_slug/:id.:format' => 'authorizables#update'

  get ':model_slug' => 'assets#index', as: :assets
  get ':model_slug/:id' => 'assets#show', as: :asset
  get ':model_slug/:id/edit' => 'assets#edit', as: :edit_asset
  patch ':model_slug/:id' => 'assets#update'
end

app/models/asset.rb
require './lib/query_authorizer'

class Asset
  include Neo4j::ActiveNode
  include Neo4jrb::Paperclip

  include Authorizable

  property :title
  validates :title, presence: true

  property :summary

  has_neo4jrb_attached_file :image
  validates_attachment_content_type :image, content_type: ['image/jpg', 'image/jpeg', 'image/png', 'image/gif']

  property :view_count, type: Integer

  property :private, type: Boolean

  has_many :out, :categories, type: :HAS_CATEGORY

  has_many :in, :creators, type: :CREATED, model_class: :User

  has_many :in, :viewers, rel_class: :View, model_class: :User

  SecretSauceRecommendation = Struct.new(:asset, :score)

  def self.for_query(query)
    all.where(title: /.*#{query}.*/i)
  end

  def secret_sauce_recommendations
    query_as(:source)
      .match('source-[:HAS_CATEGORY]->(category:Category)<-[:HAS_CATEGORY]-(asset:Asset)')
      .break
      .optional_match('source<-[:CREATED]-(creator:User)-[:CREATED]->asset')
      .break
      .optional_match('source<-[:VIEWED]-(viewer:User)-[:VIEWED]->asset')
      .limit(5)
      .order('score DESC')
      .pluck(
        :asset,
        '(count(category) * 2) +
         (count(creator) * 4) +
         (count(viewer) * 0.1) AS score').map do |other_asset, score|
      SecretSauceRecommendation.new(other_asset, score)
    end
  end

  def name
    title
  end

  def as_json(_options = {})
    {self.class.model_slug =>
      {id: id,
       title: title,
       name: title,
       image_url: image.url,
       model_slug: self.class.model_slug}
     }
  end

  def self.descendants
    Rails.application.eager_load! if Rails.env == 'development'
    Neo4j::ActiveNode::Labels._wrapped_classes.select { |klass| klass < self }
  end

  def self.model_slug
    name.tableize
  end

  def self.properties
    attributes.keys - Asset.attributes.keys
  end

  def self.authorized_for(user)
    require './lib/query_authorizer'
    QueryAuthorizer.new(all(:asset).categories(:category, nil, optional: true))
      .authorized_query([:asset, :category], user)
      .with('DISTINCT asset AS asset')
      .proxy_as(self, :asset)
  end

  def self.authorized_properties(user)
    authorized_properties_query(user).pluck(:property)
  end

  def self.authorized_properties_and_levels(user)
    authorized_properties_query(user).pluck(:property, :level)
  end

  def self.authorized_properties_query(user)
    query = property_name_and_uuid_query
            .merge(model: {Model: {name: name}})
            .on_create_set(model: {private: false})
            .break
            .merge('model-[:HAS_PROPERTY]->(property:Property {name: property_name})')
            .on_create_set(property: {private: false})
            .on_create_set('property.uuid = uuid')
            .with(:property)

    ::Property # rubocop:disable Lint/Void
    QueryAuthorizer.new(query).authorized_query(:property, user)
  end

  def self.property_name_and_uuid_query
    properties_and_uuids = properties.map do |property|
      [property, SecureRandom.uuid]
    end

    Neo4j::Session.current.query
      .with('{properties_and_uuids} AS properties_and_uuids')
      .unwind('properties_and_uuids AS property_and_uuid')
      .params(properties_and_uuids: properties_and_uuids)
      .with('property_and_uuid[0] AS property_name, property_and_uuid[1] AS uuid')
  end

  def self.authorized_associations
    associations.except(*Asset.associations.keys)
  end
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  def home
  end

  def index
    @assets = model_class_scope.with_associations(:categories)
  end

  def show
    @asset = asset

    render file: 'public/404.html', status: :not_found, layout: false if !@asset

    custom_view_path = "#{@asset.class.name.tableize}/show"
    has_custom_view = Dir.glob(Rails.root.join("app/views/#{custom_view_path}.html.*")).present?
    render custom_view_path if has_custom_view
  end

  def edit
    @asset = asset

    render file: 'public/404.html', status: :not_found, layout: false if !@asset
  end

  def update
    @asset = asset
    @asset.update(params[:book])

    redirect_to action: :edit
  end

  def asset
    model_class_scope.find(params[:id])
  end

  def model_class_scope
    model_class.authorized_for(current_user)
  end
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/views/assets/_cards.html.slim
- grouped_assets = assets.group_by(&:class)

- grouped_assets.each do |model_class, asset_group|
  - if grouped_assets.size > 1
    h2 = model_class.name.pluralize.humanize

  - properties = model_class.properties

  .ui.link.cards
    - asset_group.each do |asset|
      - category_count = asset.categories.to_a.size
      .card
        .content
          - if asset.private?
            .right.floated.meta
              i.hide.large.red.icon
          .header = link_to asset.title, asset_path(asset)
        .image = image_tag asset.image.url if image_tag asset.image.url.present?
        .content

        - categories = asset.categories.sort_by(&:name)
        - categories[0,2].each do |category|
          .extra.content
            i class="#{category.icon_class || 'folder'} icon"
            = link_to category.name, category
        - if categories.size > 2
          .extra.content
            i.ellipsis.horizontal.icon
            | more categories

app/views/assets/edit.html.slim
= javascript_include_tag 'jquery.datetimepicker', 'data-turbolinks-track' => true
= stylesheet_link_tag    'jquery.datetimepicker', media: 'all', 'data-turbolinks-track' => true


= form_for @asset, url: url_for(action: :update), html: {class: 'ui form'} do |f|
  .field
    label Title

    = f.text_field :title

  = image_tag @asset.image.url, class: 'ui medium image'
  .field
    label Image

    = f.file_field :image

  - @asset.class.authorized_properties_and_levels(current_user).each do |property, level|
    .field
      label = property.name.humanize

      = render partial: 'properties/property', locals: {property: property, asset: @asset, level: level, form: f}


  = f.submit 'Update', class: 'ui button'

app/views/assets/index.html.slim
= render partial: 'assets/cards', locals: {assets: @assets}

app/views/assets/show.html.slim
- if @current_user_is_admin
  a.ui.labeled.icon.button.right.floated data-authorizable="#{@asset.to_json}"
    | Edit Permissions

a.ui.labeled.icon.button.right.floated href="#{edit_asset_path(id: @asset)}"
  i.edit.icon
  | Edit

.ui.header
  = image_tag @asset.image.url, class: 'ui image tiny rounded'
  .content
    = @asset.title

table.ui.table.celled.very.padded.rounded
  - @asset.class.authorized_properties(current_user).each do |property|
    tr
      th data-authorizable="#{property.to_json}"
        = property.name.humanize
        | &nbsp;&nbsp;
        - if property.private?
          i.red.hide.icon
      td = render partial: 'properties/property', locals: {property: property, asset: @asset, level: 'read'}

  tr
    th Created
    td = @asset.created_at

  tr
    th Last updated
    td = @asset.updated_at

  - @asset.class.authorized_associations.each do |name, association|
    tr
      th = name.to_s.humanize
      td
        - case association.type
        - when :has_one
          - object = @asset.send(name)
          = link_to object.title, asset_path(object)
        - when :has_many
          ul
            - @asset.send(name).each do |object|
              li = link_to object.title, asset_path(object)

  tr
    th Categories
    td
      ul.ui.relaxed.divided.list
        - @asset.categories.each do |category|
          li.item = link_to category.name, category

h1 Recommendations

table.ui.celled.table
  thead
    tr
      th Title
      th Score
  tbody
    - @asset.secret_sauce_recommendations.each do |recommendation|
      tr
        td = link_to recommendation.asset.title, asset_path(recommendation.asset)
        td = recommendation.score