config/routes.rb
Rails.application.routes.draw do
  mathjax 'mathjax'

  # Routes for GraphGist portal
  get 'graph_gists/submit' => 'graph_gists#submit'
  get 'graph_gists/preview' => 'graph_gists#preview', as: :graph_gist_preview

  get 'graph_gists/search' => 'graph_gists#search'

  # Routes for asset_portal
  resources :groups
  root 'assets#home'

  devise_for :users

  resources :categories
  resources :groups do
    member do
      get :users_to_add
    end
  end
  resources :users

  get 'models' => 'models#index', as: :models
  get 'models/:name' => 'models#show', as: :model

  get 'authorizables/user_and_group_search.json' => 'authorizables#user_and_group_search'
  get 'authorizables/:model_slug/:id.:format' => 'authorizables#show'
  put 'authorizables/:model_slug/:id.:format' => 'authorizables#update'

  get ':model_slug' => 'assets#index', as: :assets
  get ':model_slug/:id' => 'assets#show', as: :asset
  get ':model_slug/:id/edit' => 'assets#edit', as: :edit_asset
  patch ':model_slug/:id' => 'assets#update'
end

app/views/layouts/_change_permissions_modal.html.slim
script type="text/x-handlebars"
  .ui.modal
    i.close.icon

    .header Change permissions for {{object.name}}
    .image.content
      | {{#if object.image_url}}
      .ui.medium.image
        img src="{{object.image_url}}"
      | {{/if}}

      .description

        <div class="ui search {{if searching 'loading' ''}}">
          .ui.icon.input
            | {{input type="text" placeholder="User or group" class="prompt" value=user_and_group_search}}
            i.add.circle.icon

          <div id="modal-search-results" class="results transition {{if user_and_group_results_present 'visible' ''}}">
            .ui.two.column.grid
              - %w(user group).each do |result_type|
                | {{#if #{result_type}_results.length}}
                .eight.wide.column
                  table.ui.celled.striped.table
                    tr
                      th colspan="3"
                        h2
                          i class="#{result_type == 'user' ? 'user' : 'users'} icon"
                          = result_type.humanize.pluralize                         
                    | {{#each #{result_type}_results as |result|}}
                    tr
                      td
                        | {{result.name}}
                      td
                        .ui.large.buttons
                          <button {{action "add_#{result_type}" result 'read'}} class="ui button green icon">Read</button>
                          .or
                          <button {{action "add_#{result_type}" result 'write'}} class="ui button red icon">Write</button>
                    | {{/each}}
                | {{/if}}

          </div>
        </div>

          .inline.field
            .ui.checkbox
              | {{input type="checkbox" name="private" checked=object.private}}
              label Private?
          - %w(user group).each do |entity_type|
            | {{#if #{entity_type}_permissions}}
            .ui.segment.padded
              .ui.form
                .ui.header
                  i class="#{entity_type == 'user' ? 'user' : 'users'} icon"
                  | #{entity_type.humanize.pluralize} allowed access
                table.ui.definition.table
                  | {{#each object.#{entity_type}_permissions as |#{entity_type}_permission|}}
                  tr
                    td
                      label
                        | {{#{entity_type}_permission.#{entity_type}.name}}
                    td
                      .field
                        .ui.radio.checkbox
                          | {{ radio-button name=#{entity_type}_permission.#{entity_type}.id value='read' groupValue=#{entity_type}_permission.level }}
                          label Read
                    td
                      .field
                        .ui.radio.checkbox
                          | {{ radio-button name=#{entity_type}_permission.#{entity_type}.id value='write' groupValue=#{entity_type}_permission.level }}
                          label Write
                    td
                      <button {{action "remove_#{entity_type}_permission" #{entity_type}_permission}} class="ui circular red button"><i class="remove user icon"/></button>
                  | {{/each}}

            | {{/if}}

          <button {{action "update_permissions" target="controller"}} class="ui button positive icon {{if saving 'loading' ''}}"><i class="write icon"/>Update Permissions</button>

    .actions
      .ui.positive.right.labeled.icon.button.done
        | Done
        i.checkmark.icon

  scss:
    .ui.search > #modal-search-results {
      width: 600px;
      padding: 1em;
    }

app/views/layouts/_menu.html.slim
#menu.ui.secondary.pointing.menu
  - Asset.descendants.each do |model_class|
    - path = assets_path(model_slug: model_class.model_slug)
    = link_to model_class.name.pluralize.humanize, path, class: "item #{'active' if request.path.match(/^#{path}/)}"

  .right.menu
    .ui.item
      #graph-gist-search.ui.search
        .ui.icon.input
          input.prompt type="text" placeholder="Search for a GraphGist..."
          i.search.icon
        .results

        coffee:
          $.fn.api.settings.api =
            'search graph_gists' : '/graph_gists/search?query={query}'

          #$('#graph-gist-search').api action: 'search graph_gists'

          $('#graph-gist-search').search
            apiSettings:
              action: 'search graph_gists'
            debug: true
            verbose: true

    .ui.item = link_to 'Submit GraphGist', graph_gists_submit_path

    .ui.item = link_to 'Groups', groups_path if @current_user_is_admin
  - if user_signed_in?
    .ui.item Logged in as #{current_user.name}
    .ui.item = link_to 'Sign out', destroy_user_session_path, method: 'delete'
  - else
    .ui.item = link_to 'Sign in', new_user_session_path
    .ui.item = link_to 'Sign up', new_user_registration_path

app/views/layouts/_twitter_meta_tags.html.slim
meta name="twitter:site" content="@neo4j"
meta name="twitter:domain" content="http://neo4j.org"

- if @asset
  - if @asset.creators.count > 0
    - # Is this the right one?  Difference between uploader and author
    meta name="twitter:creator" content="@#{@asset.creators[0].twitter_username}"

  - if @asset.title
    meta name="twitter:title" content="#{@asset.title}"

  meta name="twitter:description" content="#{@asset.summary}"

  meta name="twitter:card" content="#{(@asset.image ? 'summary_large_image' : 'summary')}"

  meta name="twitter:image:src" content="#{@asset.image.url || '/assets/img/neo4j/neo4j-logo.png'}"

app/views/layouts/application.html.slim
doctype html

html

  head
    title AssetPortal
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true

    = render partial: 'layouts/twitter_meta_tags'

    javascript:
      var current_user = #{current_user.to_json.html_safe}.user;

    = javascript_include_tag 'application', 'data-turbolinks-track' => true

    - controller = params[:controller].to_sym

    - if ![:users, :groups].include?(controller)
      = javascript_include_tag 'ember_apps/permissions_modal', 'data-turbolinks-track' => true

    = csrf_meta_tags

  body

    = render partial: 'layouts/menu'

    - if notice.present?
      p.ui.green.message
        i.close.icon
        = notice
    - if alert.present?
      p.ui.yellow.message
        i.close.icon
        = alert

    .ui.container

      = yield

    - if @current_user_is_admin
      #change-object-permissions

      - if !request.env['HTTP_X_XHR_REFERER']
        = render partial: 'layouts/change_permissions_modal', locals: {asset: @asset}